### ISSUE TITLE
Forgot password does not send email

### ISSUE THREAD

**Issue by chung88** [akoleti/dataset-submission-#1]
1.  Register new user
2.- Email already exists. Please specify password.
3.- Forgot password
4.- Failed to send email
![image](https://user-images.githubusercontent.com/3586358/35278302-978fb194-0017-11e8-86ee-b84ff15b813b.png)

1.-![image](https://user-images.githubusercontent.com/3586358/35278234-5aaf662a-0017-11e8-86c4-89c3aad26cb7.png)

3.-
![image](https://user-images.githubusercontent.com/3586358/35278290-85a3ebbc-0017-11e8-89bd-5abca30d3c28.png)

**Comment by akoleti** [comment]
Please try again and let me know if you still have issue with this.
