### ISSUE TITLE
Authentic user email address

### ISSUE THREAD

**Issue by chung88** [akoleti/dataset-submission-#2]
Tester does not have an authentic email address, email confirmation.  Is this OK?

![image](https://user-images.githubusercontent.com/3586358/35278573-818b7274-0018-11e8-8b40-8c4f21fcfaaf.png)

**Comment by akoleti** [comment]
This Should work Now. Please check and close the issue.

**Comment by chung88** [comment]
![image](https://user-images.githubusercontent.com/3586358/35286431-0069d9fe-002e-11e8-9c78-d059e0a4f81c.png)
