### ISSUE TITLE
user name display on page is hard to see

### ISSUE THREAD

**Issue by chung88** [akoleti/dataset-submission-#3]
The username is black on blue, hard to see.

![image](https://user-images.githubusercontent.com/3586358/35278707-d8ea3f0a-0018-11e8-8081-85f32a5baca5.png)

**Comment by chung88** [comment]
after forgot password, I cannot read  "You should receive an email shortly with further instructions."
![image](https://user-images.githubusercontent.com/3586358/35285070-6e3504bc-002a-11e8-8f58-bc68f2b984f3.png)

**Comment by akoleti** [comment]
This should be fixed as well.
