### ISSUE TITLE
unable to see CEDAR templates as tester

### ISSUE THREAD

**Issue by chung88** [akoleti/dataset-submission-#4]
![image](https://user-images.githubusercontent.com/3586358/35278940-89b4a352-0019-11e8-8eb7-c56bc32e480c.png)

**Comment by chung88** [comment]
![image](https://user-images.githubusercontent.com/3586358/35279179-4ea04f90-001a-11e8-98ef-8dcc3b45b9c8.png)

**Comment by akoleti** [comment]
For the first time you will be prompted to  a screen where you should click LINCS to see the templates
![image](https://user-images.githubusercontent.com/12258558/35287731-152b5f90-0031-11e8-9140-196fa11b109b.png)

**Comment by akoleti** [comment]
Do any one else have this issue ?

**Comment by chung88** [comment]
I am in, it is working.

________________________________
