### ISSUE TITLE
DST Corner Link Does Not Function

### ISSUE THREAD

**Issue by djc183** [akoleti/dataset-submission-#5]
Upper left corner "button" for DST does not go back to the main site, instead it gives a 404 error.

**Comment by akoleti** [comment]
This should work now. Please check and close the issue.

**Comment by djc183** [comment]
Looks good, thanks

**Comment by djc183** [comment]
Still not working on the submit reagent metadata page.

**Comment by akoleti** [comment]
it should work now

**Comment by djc183** [comment]
Looks good
